# Create a new user without avatar
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "robocop@notfound.local",
  "name": "Keks",
  "password": "123456"
}

###

# Create a new user with avatar
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="email"

robocop-5@notfound.local
--boundary
Content-Disposition: form-data; name="password"

123456
--boundary
Content-Disposition: form-data; name="name"

Keks
--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpeg

< ./avatar.jpg
--boundary--

###

# Login user by email and password
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "robocop@notfound.local",
  "password": "123456"
}

###

# Change password
POST http://localhost:3000/api/users/password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2ExZjEyYzI5YjRkZjllNTJmMDgwMjUiLCJlbWFpbCI6InJvYm9jb3BAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODY3MjEyMSwiZXhwIjoxNzM4NjczMDIxfQ.ZgrhL9_zsrx9usP2O0aYzOS-Vugjlh3uXIoSU1UyI34
Content-Type: application/json

{
  "oldPassword": "123456",
  "newPassword": "0123456"
}


###

# Get new JWT pair
POST http://localhost:3000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2ExZjEyYzI5YjRkZjllNTJmMDgwMjUiLCJlbWFpbCI6InJvYm9jb3BAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODY3MjEyMSwiZXhwIjoxNzM4NjczMDIxfQ.ZgrhL9_zsrx9usP2O0aYzOS-Vugjlh3uXIoSU1UyI34

###

# Get user detail by ID
GET http://localhost:3000/api/users/67a1f2b229b4df9e52f08036 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2ExZjEyYzI5YjRkZjllNTJmMDgwMjUiLCJlbWFpbCI6InJvYm9jb3BAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODY5MjY4MSwiZXhwIjoxNzM4NjkzNTgxfQ.hVJPwq9n7AJBmjM7Z1_m2NBSqCS92rlFJDNeRHLQ6Zg

###

# Add subcription
POST http://localhost:3000/api/users/toggle-subscribe/67a1f2b229b4df9e52f08036 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2ExZjEyYzI5YjRkZjllNTJmMDgwMjUiLCJlbWFpbCI6InJvYm9jb3BAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODY5MjY4MSwiZXhwIjoxNzM4NjkzNTgxfQ.hVJPwq9n7AJBmjM7Z1_m2NBSqCS92rlFJDNeRHLQ6Zg

###

# Create a new post
POST http://localhost:3000/api/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2ExZjEyYzI5YjRkZjllNTJmMDgwMjUiLCJlbWFpbCI6InJvYm9jb3BAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODY5NjI3MSwiZXhwIjoxNzM4Njk3MTcxfQ.SZtJAob7OsjxKnRgTn55XjoGyDlOl7lC9aIEMLQsTdU
Content-Type: application/json

{
  "type": "TEXT",
  "tags": ["cats", "new"],
  "content": {
    "title": "Тест API Gateway11 Тест API Gateway",
    "teaser": "Текст с анонсом публикации11. Минимальная длина 50 символов, максимальная 255.",
    "text": "Текст публикации (обязательно). Минимальная длина 100 символов, максимальная 1024 символа. Текст публикации (обязательно)."
  }
}
###

# Create a new PHOTO post
POST http://localhost:3000/api/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2ExZjEyYzI5YjRkZjllNTJmMDgwMjUiLCJlbWFpbCI6InJvYm9jb3BAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODY5MjY4MSwiZXhwIjoxNzM4NjkzNTgxfQ.hVJPwq9n7AJBmjM7Z1_m2NBSqCS92rlFJDNeRHLQ6Zg
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="type"

PHOTO
--boundary
Content-Disposition: form-data; name="file"; filename="avatar.jpg"
Content-Type: image/jpeg

< ./avatar.jpg
--boundary--

###

# Get all posts
GET http://localhost:3000/api/posts HTTP/1.1

###

# Get posts with filter

GET http://localhost:3000/api/posts?limit=2&sortDirection=desc&page=1&search=Тест HTTP/1.1

###

# Get post by id
GET http://localhost:3000/api/posts/392d4c1b-de74-49d0-b325-b07cbbaebdf3 HTTP/1.1

###

# Add like to post
POST http://localhost:3000/api/posts/addLike/6d308040-96a2-4162-bea6-2338e9976540
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2ExZjEyYzI5YjRkZjllNTJmMDgwMjUiLCJlbWFpbCI6InJvYm9jb3BAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODY5NjI3MSwiZXhwIjoxNzM4Njk3MTcxfQ.SZtJAob7OsjxKnRgTn55XjoGyDlOl7lC9aIEMLQsTdU
###

# Delete like to post
POST http://localhost:3000/api/posts/deleteLike/0ac9ffad-9145-427d-b1ab-46fe4a5a6120
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2ExZjEyYzI5YjRkZjllNTJmMDgwMjUiLCJlbWFpbCI6InJvYm9jb3BAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODY3MjEyMSwiZXhwIjoxNzM4NjczMDIxfQ.ZgrhL9_zsrx9usP2O0aYzOS-Vugjlh3uXIoSU1UyI34

###

# Make a repost
POST http://localhost:3000/api/posts/repost/0ac9ffad-9145-427d-b1ab-46fe4a5a6120
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2ExZjEyYzI5YjRkZjllNTJmMDgwMjUiLCJlbWFpbCI6InJvYm9jb3BAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODY3MjEyMSwiZXhwIjoxNzM4NjczMDIxfQ.ZgrhL9_zsrx9usP2O0aYzOS-Vugjlh3uXIoSU1UyI34

###

# Delete a post
DELETE http://localhost:3000/api/posts/0ac9ffad-9145-427d-b1ab-46fe4a5a6120
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2ExZjEyYzI5YjRkZjllNTJmMDgwMjUiLCJlbWFpbCI6InJvYm9jb3BAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODY3MjEyMSwiZXhwIjoxNzM4NjczMDIxfQ.ZgrhL9_zsrx9usP2O0aYzOS-Vugjlh3uXIoSU1UyI34

###

# Update a post
PATCH http://localhost:3000/api/posts/0ac9ffad-9145-427d-b1ab-46fe4a5a6120
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2ExZjEyYzI5YjRkZjllNTJmMDgwMjUiLCJlbWFpbCI6InJvYm9jb3BAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODY3MjEyMSwiZXhwIjoxNzM4NjczMDIxfQ.ZgrhL9_zsrx9usP2O0aYzOS-Vugjlh3uXIoSU1UyI34
Content-Type: application/json

{
  "type": "TEXT",
  "tags": ["cats", "new"],
  "content": {
    "title": "Updated. Тест API Gateway Тест API Gateway",
    "teaser": "Текст с анонсом публикации. Минимальная длина 50 символов, максимальная 255.",
    "text": "Текст публикации (обязательно). Минимальная длина 100 символов, максимальная 1024 символа. Текст публикации (обязательно)."
  }
}

###

# Create a comment to a post
POST http://localhost:3000/api/posts/0ac9ffad-9145-427d-b1ab-46fe4a5a6120/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2ExZjEyYzI5YjRkZjllNTJmMDgwMjUiLCJlbWFpbCI6InJvYm9jb3BAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODY3MjEyMSwiZXhwIjoxNzM4NjczMDIxfQ.ZgrhL9_zsrx9usP2O0aYzOS-Vugjlh3uXIoSU1UyI34
Content-Type: application/json

{
  "text": "This is text of a comment."
}

###

# Get comments to a post
GET http://localhost:3000/api/posts/0ac9ffad-9145-427d-b1ab-46fe4a5a6120/comments

###

# Delete comment
DELETE  http://localhost:3000/api/comments/0ac9ffad-9145-427d-b1ab-46fe4a5a6120
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2ExZjEyYzI5YjRkZjllNTJmMDgwMjUiLCJlbWFpbCI6InJvYm9jb3BAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTczODY3MjEyMSwiZXhwIjoxNzM4NjczMDIxfQ.ZgrhL9_zsrx9usP2O0aYzOS-Vugjlh3uXIoSU1UyI34

###

# Send new posts notifications
GET http://localhost:3000/api/posts/notify

###
