# Create a new user
POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user111@notfound.local",
  "name": "user111",
  "password": "123456",
  "avatar": "https://yandex.ru/search/111.png"
}

###

# Get user by ID
GET http://localhost:3001/api/auth/679a2bd04f1c1b4fee166d2f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzlhMmJkMDRmMWMxYjRmZWUxNjZkMmYiLCJlbWFpbCI6InVzZXIxMTFAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoidXNlcjExMSIsImlhdCI6MTczODE2MjM2MCwiZXhwIjoxNzM4MTYzMjYwfQ.BVf0fN3VVY_oJExsqrm-r1iQ_-VzDmLiu76VzAIxxWA

###

# Login user by email and password
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user111@notfound.local",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:3001/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzlhMmJkMDRmMWMxYjRmZWUxNjZkMmYiLCJlbWFpbCI6InVzZXIxMTFAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoidXNlcjExMSIsImlhdCI6MTczODE2MjM2MCwiZXhwIjoxNzM4MTYzMjYwfQ.BVf0fN3VVY_oJExsqrm-r1iQ_-VzDmLiu76VzAIxxWA
###

# Check user token
POST http://localhost:3001/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzlhMmJkMDRmMWMxYjRmZWUxNjZkMmYiLCJlbWFpbCI6InVzZXIxMTFAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoidXNlcjExMSIsImlhdCI6MTczODE2MjM2MCwiZXhwIjoxNzM4MTYzMjYwfQ.BVf0fN3VVY_oJExsqrm-r1iQ_-VzDmLiu76VzAIxxWA

###
