# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "name": "Keks",
  "password": "123456",
  "avatar": "keks-img.png",
}

###

# Get user by ID
GET http://localhost:3000/api/auth/676097e1f1de7f4bac72a181 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/676097e1f1de7f4bac72a181 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJlbWFpbCI6IjY2aWx1c2VyQG5vdGZvdW5kLmxvY2FsIiwibmFtZSI6IjY2S2Vrc29uZ28iLCJpYXQiOjE3MzczOTg0ODQsImV4cCI6MTczNzM5ODc4NH0.7VdyzopDe6j98QVgK1gDO0ICJbskUsLYtN_bt-Rti2o

###
